"""Initial migration

Revision ID: 5ab4ee8a296f
Revises: 
Create Date: 2024-12-27 13:21:16.878710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5ab4ee8a296f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_length', sa.Float(), nullable=False),
    sa.Column('timber_spacing', sa.Float(), nullable=False),
    sa.Column('chair_alignment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('flange_width', sa.Float(), nullable=True),
    sa.Column('flange_depth', sa.Float(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groove_width', sa.Float(), nullable=False),
    sa.Column('groove_depth', sa.Float(), nullable=False),
    sa.Column('fit_adjustment', sa.Float(), nullable=True),
    sa.Column('rib_spacing', sa.Float(), nullable=True),
    sa.Column('jaw_height', sa.Float(), nullable=True),
    sa.Column('placement_offset', sa.Float(), nullable=False),
    sa.Column('timber_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timber_id'], ['timber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chair')
    op.drop_table('timber')
    op.drop_table('track')
    # ### end Alembic commands ###
