"""Describe your changes here

Revision ID: abcef58abfa0
Revises: 54fbe97df81c
Create Date: 2024-12-27 20:52:40.115932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abcef58abfa0'
down_revision: Union[str, None] = '54fbe97df81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chair', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('S1', name='chairtype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chair', 'type',
               existing_type=sa.Enum('S1', name='chairtype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
